### ISSUE TITLE
Use json output of scilla-fmt instead of s-expression

### ISSUE THREAD

**Issue by its-saeed** [Zilliqa/hardhat-scilla-plugin#2]
scilla-fmt --json --deannot --human-readable

**Comment by sal-zilliqa** [comment]
I'm working on this at the moment.

**Comment by sal-zilliqa** [comment]
The JSON output of scilla-fmt contains less information than the s-expression one. We use some of the information in the s-expression output that isn't in the JSON one so switching to the JSON isn't possible.
