### ISSUE TITLE
ScillaParser can't parse ecdsa contract

### ISSUE THREAD

**Issue by its-saeeed** [Zilliqa/hardhat-scilla-plugin#22]
Parsing [ecdsa.scilla](https://github.com/Zilliqa/scilla-test-suite/blob/main/smart-contracts/ecdsa.scilla) fails with:

```
Error in plugin hardhat-scilla-plugin: Encountered unexpected field type Address,CodeAddr
```

**Comment by its-saeed** [comment]
Same with [codehash.scilla](https://github.com/Zilliqa/scilla-test-suite/blob/main/smart-contracts/codehash.scilla)
